Remove invalid unstable configuration and run CI build with both nightly and stable Rust toolchains (#173)
* Remove invalid unstable configuration

These are no longer valid in the latest nightly. They fail with the
following message:

```
error: panic_immediate_abort is now a real panic strategy! Enable it with `panic = "immediate-abort"` in Cargo.toml, or with the compiler flags `-Zunstable-options -Cpanic=immediate-abort`. In both cases, you still need to build core, e.g. with `-Zbuild-std`
  --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:36:1
   |
36 | / compile_error!(
37 | |     "panic_immediate_abort is now a real panic strategy! \
38 | |     Enable it with `panic = \"immediate-abort\"` in Cargo.toml, \
39 | |     or with the compiler flags `-Zunstable-options -Cpanic=immediate-abort`. \
40 | |     In both cases, you still need to build core, e.g. with `-Zbuild-std`"
41 | | );
   | |_^
```

* Simplify matrix configuration in `build-demos-std`

`include` can expand existing matrix configurations, which doesn't seem
to be necessary here:
https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations#expanding-or-adding-matrix-configurations

This new configuration is simpler, but should be functionally
equivalent.

* Run CI build on both stable and nightly

This adds more duplicated CI configuration, which is undesirable. But I
don't know if there are better ways to do this, and if merging some of
those workflows would bring different disadvantages.

Leaves out the Miri workflow, as that only runs on nightly in the first
place.

* Simplify installation of Rust targets

Now that `rust-toolchain` is in use, we can do that more simply.