Remove invalid unstable configuration (#175)
These are no longer valid in the latest nightly. They fail with the
following message:

```
error: panic_immediate_abort is now a real panic strategy! Enable it with `panic = "immediate-abort"` in Cargo.toml, or with the compiler flags `-Zunstable-options -Cpanic=immediate-abort`. In both cases, you still need to build core, e.g. with `-Zbuild-std`
  --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:36:1
   |
36 | / compile_error!(
37 | |     "panic_immediate_abort is now a real panic strategy! \
38 | |     Enable it with `panic = \"immediate-abort\"` in Cargo.toml, \
39 | |     or with the compiler flags `-Zunstable-options -Cpanic=immediate-abort`. \
40 | |     In both cases, you still need to build core, e.g. with `-Zbuild-std`"
41 | | );
   | |_^
```